Add poetry files with pre-commit library and hooks
uchicago-capp-30320/new-arrivals-chi pull request #20
Opened 2024-04-11 03:23 UTC by aaronhaefner

### Describe your changes

This PR closes #12 by adding `poetry.lock` and `pyproject.toml` files to the repo.

### Non-obvious technical information

The poetry environment includes python and pre-commit currently. This is to implement pre-commit hooks that check and auto-format code using rules established in the `.pre-commit-config.yaml` file. 

To test the hooks you can use the command flow below

```commandline
poetry shell
```

Create a `test_pc.py" file and add incorrectly formatted content like below. 
```commandline
code test_pc.py //or touch
```
```commandline
###  testing git pre-commit hook
def   greet(name ):
    print(   "Hello, "   + name)
```

Then run
```commandline
git add test_pc.py
pre-commit run --all-files
```

Most hooks auto-format code but some items have to be edited manually but this is made clear when running the command. All testes must pass before code can be committed.

### Checklist before requesting a review (delete this and below before requesting review for PR)

- [x] pre-commit run --all-files
- [ ] pytest.py
- [x] Link issue 
- [x] Update relevant documentation if applicable: doc strings, readme, poetry.

2024-04-11 18:40 UTC, klinkoberstar requested changes
@aaronhaefner see the issue i had in the comments for the poetry.lock file!

2024-04-11 18:40 UTC, klinkoberstar commented on poetry.lock
when i ran it on my machine, i had to run 
```
poetry remove pre-commit
poetry add pre-commit
```
and then everything ran as expected.

Doing this made a chance to the poetry.lock file, adding `category = "main"` as shown below. I pasted the block below with the line before and after to see where the change happened:

```
description = "A framework for managing and maintaining multi-language pre-commit hooks."
category = "main"
optional = false
```

Curious if @xiomara0 will run into the same issue!

2024-04-11 21:16 UTC, aaronhaefner commented on poetry.lock
What's the error when you run `poetry shell`?

2024-04-11 21:27 UTC, klinkoberstar commented on poetry.lock
I was able to run `poetry shell` with no issue.

The error occurs when i try to run `pre-commit run --all-files` which gave me the following error:

```
zsh: command not found: Pre-commit
```

Tried `poetry add pre-commit` but as I suspected based on reading the `poetry.toml` file it's already there
```
poetry add pre-commit
The following packages are already present in the pyproject.toml and will be skipped:

  • pre-commit

If you want to update it to the latest compatible version, you can use `poetry update package`.
If you prefer to upgrade it to the latest available version, you can use `poetry add package@latest`.

Nothing to add.
```

Next, Itried to check the filepath for `pre-commit` by running:

```
poetry run which pre-commit
```

This didn't return anything so I tried removing and adding pre-commit again using the code in my initial comment:

```
poetry remove pre-commit
poetry add pre-commit
```

I ran `poetry run which pre-commit` again and this time I got a filepath

After that, I was able to proceed as instructed with no issues.

It might just be a bug with poetry? If you're not worried about it I'll approve the PR!

2024-04-11 22:04 UTC, aaronhaefner commented on poetry.lock
`zsh: command not found: Pre-commit` might mean something is missing in your system `PATH` variable, like its not being directed to the "right" python environment that contains poetry/pre-commit.

We should have another person try it out - I haven't been able to replicate it.

2024-04-12 00:56 UTC, klinkoberstar approved these changes

2024-04-12 01:23 UTC, merged